AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "vendor/**/*"
    - "spec/**/*"

Layout/LineLength:
  Max: 180

Layout/IndentationWidth:
  Width: 2

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false
