# frozen_string_literal: true

source 'https://rubygems.org'

gem 'i18n'
gem 'sequel'
gem 'sinatra'
gem 'sqlite3'

group :development, :test do
  gem 'rubocop', require: false
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
